const mongoose = require('mongoose');
var ObjectId = require('mongoose').Types.ObjectId;

const mongoosePort = require('../env_variables/env_vars.json').mongoosePort
mongoose.connect(mongoosePort);

const express = require('express');
const bodyParser = require('body-parser');

/**
 * get all the available info of a song for the user request.
 * @module getSongRoutes
 */
const getSongRoutes = (app, fs) => {
    // showing the liked albums
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));
    /**
    * This function gets all the available info of the song that the user requested for.
    * @name get/Song/:songId
    * @function
    * @memberof module:getSongRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the song's id generated by the mongoBD as requested from the postman
    * @param {Array} res it shows all the available info of the song that the user requested for.
    */
    app.get('/Song/:songId', (req, res) => {
        mongoose.connection.db.collection('songs',function(err, collection){
             collection.find({_id:new ObjectId(req.params.songId)}).toArray(function(err,docs){
                    if (err) {
                        throw err;

                    }
                    res.send(docs[0]);
                    
                });
        });
    });
}

module.exports = getSongRoutes;