
const mongoose = require('mongoose');
var ObjectId = require('mongoose').Types.ObjectId;

const mongoosePort = require('../env_variables/env_vars.json').mongoosePort
mongoose.connect(mongoosePort);

const express = require('express');
const bodyParser = require('body-parser');

const auth = require('../middlewares/token_auth');
/**
 * liking/unlinking album requests.
 * @module likedAlbumsRoutes
 */
const likedAlbumsRoutes = (app, fs) => {
    // showing the liked albums
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));
    /**
    * This function gets the liked albums that the user liked and requested for.
    * Then it shows all the albums the user liked.
    * @name get/likedAlbums
    * @function
    * @memberof module:likedAlbumsRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the user's id generated by the mongoBD as requested from the postman
    * @param {Array} res it shows all the albums that the user liked and requested for.
    */

    app.get('/likedAlbums', auth, (req, res) => {
        mongoose.connection.db.collection('users',function(err, collection){
             collection.find({_id:new ObjectId(req.userId)}).toArray(function(err,docs){

                if (err) {
                    throw err;

                }

                arr = []

                for (var i = 0; i < docs[0].likedAlbums.length; i++) {
                    arr.push(new ObjectId(docs[0].likedAlbums[i]))
                }

                mongoose.connection.db.collection('albums',function(err, collection2){
                    collection2.find({_id:{ $in: arr}}).toArray(function(err,docs2){
       
                       if (err) {
                           throw err;
                       }
                       res.send(docs2);
                    });
                   });
             });
            });
    });
    // liking an album
    
    
    /**
    * This function likes an album that the user liked and requested for.
    * Then it updates the info of the user and the info of the album.
    * @name put/likedAlbums
    * @function
    * @memberof module:likedAlbumsRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the album's id generated by the mongoBD as requested from the postman.
    * @param {*} userId it adds the the user id in the array of the userID in the album.
    * @param {*} likedAlbums it adds the the album id in the array of the albumID in the album.
    */
    app.put('/likedAlbums', auth, (req, res, next) => {
        var query;
        mongoose.connection.db.collection('albums',function(err, collection){
            collection.updateOne(
                {_id: new ObjectId(req.body.albumId)},
                {$push:{ userId :req.userId}}
            );
        });
        mongoose.connection.db.collection('users',function(err, collection){
            collection.updateOne(
                {_id: new ObjectId(req.userId)},
                {$push:{ likedAlbums :req.body.albumId}}
            );
        });
        res.end();
      });
    // unliking an album

    /**
    * This function likes an album that the user liked and requested for.
    * Then it updates the info of the user and the info of the album.
    * @name put/unlikeAlbums
    * @function
    * @memberof module:likedAlbumsRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the album's id generated by the mongoBD as requested from the postman.
    * @param {Array} userId it removes the the user id in the array of the userID in the album.
    * @param {Array} likedAlbums it removes the the album id in the array of the albumID in the album.
    */
    app.put('/unlikeAlbums', auth, (req, res) => {
        mongoose.connection.db.collection('albums',function(err, collection){
            collection.find({_id:new ObjectId (req.body.albumId)}, {userId:req.userId}).toArray(function(err,docs){
               if (err) {
                   throw err;
               }
               var arr = docs[0].userId
               if (arr.length == 0) {
                   throw err
               }else{
                    collection.updateOne(
                        {_id: new ObjectId(req.body.albumId)},
                        {$pull:{ userId :req.userId}}
                    )
                  
                }
            });
        });
        mongoose.connection.db.collection('users',function(err, collection){
            collection.find({_id:new ObjectId (req.userId)}, {likedAlbums:req.body.albumId}).toArray(function(err,docs){
               if (err) {
                   throw err;
               }
               var arr = docs[0].likedAlbums
               if (arr.length == 0) {
                   throw err
               }else{
                    collection.updateOne(
                        {_id: new ObjectId(req.userId)},
                        {$pull:{ likedAlbums :req.body.albumId}}
                    )
                  
                }
            });
        });
           res.end();
    });
};

module.exports = likedAlbumsRoutes;