
const mongoose = require('mongoose');
var ObjectId = require('mongoose').Types.ObjectId;

const mongoosePort = require('../env_variables/env_vars.json').mongoosePort
mongoose.connect(mongoosePort);

const express = require('express');
const bodyParser = require('body-parser');

const auth = require('../middlewares/token_auth');

/**
 * liking/unlinking Artists requests.
 * @module likedArtistsRoutes
 */
const likedArtistsRoutes = (app, fs) => {
    // showing the liked Artists
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));

    /**
    * This function gets the liked Artists that the user liked and requested for.
    * Then it shows all the Artists the user liked.
    * @name get/likedArtists
    * @function
    * @memberof module:likedArtistsRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the user's id generated by the mongoBD as requested from the postman
    * @param {Array} res it shows all the Artists that the user liked and requested for.
    */
    app.get('/likedArtists', auth, (req, res) => {
        mongoose.connection.db.collection('users',function(err, collection){
             collection.find({_id:new ObjectId(req.userId)}).toArray(function(err,docs){

                if (err) {
                    throw err;

                }

                arr = []

                for (var i = 0; i < docs[0].likedArtists.length; i++) {
                    arr.push(new ObjectId(docs[0].likedArtists[i]))
                }

                mongoose.connection.db.collection('users',function(err, collection2){
                    collection2.find({_id:{ $in: arr}}).toArray(function(err,docs2){
       
                       if (err) {
                           throw err;
                       }
                       res.send(docs2);
                    });
                   });
             });
            });
    });
    // liking an Artists

    /**
    * This function likes an Artists that the user liked and requested for.
    * Then it updates the info of the user and the info of the Artists.
    * @name put/likedArtists
    * @function
    * @memberof module:likedArtistsRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the user's id generated by the mongoBD as requested from the postman.
    * @param {*} followers it adds the the user id in the array of the userID in the Artists.
    * @param {*} likedArtists it adds the the Artists id in the array of the ArtistsID in the Artists.
    */
    app.put('/likedArtists', auth, (req, res, next) => {
        mongoose.connection.db.collection('users',function(err, collection){
            collection.updateOne(
                {_id: new ObjectId(req.userId)},
                {$push:{ likedArtists :req.body.artistId}}
            );
        });
        mongoose.connection.db.collection('users',function(err, collection){
            collection.updateOne(
                {_id: new ObjectId(req.body.artistId)},
                {$push:{ followers :req.userId}}
            );
        });
        res.end();
      });
    // unliking an Artists

    /**
    * This function likes an Artist that the user liked and requested for.
    * Then it updates the info of the user and the info of the Artist.
    * @name put/unlikeArtists
    * @function
    * @memberof module:likedArtistsRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the user's id generated by the mongoBD as requested from the postman.
    * @param {Array} followers it removes the the user id in the array of the userID in the Artist.
    * @param {Array} likedArtists it removes the the Artist id in the array of the ArtistID in the Artist.
    */
    app.put('/unlikeArtists', auth, (req, res) => {
        mongoose.connection.db.collection('users',function(err, collection){
            collection.find({_id:new ObjectId (req.userId)}, {likedArtists:req.body.artistId}).toArray(function(err,docs){
               if (err) {
                   throw err;
               }
               var arr = docs[0].likedArtists
               if (arr.length == 0) {
                   throw err
               }else{
                    collection.updateOne(
                        {_id: new ObjectId(req.userId)},
                        {$pull:{ likedArtists :req.body.artistId}}
                    )
                  
                }
            });
        });
        mongoose.connection.db.collection('users',function(err, collection){
            collection.find({_id:new ObjectId (req.body.artistId)}, {followers:req.userId}).toArray(function(err,docs){
               if (err) {
                   throw err;
               }
               var arr = docs[0].followers
               if (arr.length == 0) {
                   throw err
               }else{
                    collection.updateOne(
                        {_id: new ObjectId(req.body.artistId)},
                        {$pull:{ followers :req.userId}}
                    )
                  
                }
            });
        });
           res.end();
    });
};

module.exports = likedArtistsRoutes;