
const mongoose = require('mongoose');
var ObjectId = require('mongoose').Types.ObjectId;

const mongoosePort = require('../env_variables/env_vars.json').mongoosePort
mongoose.connect(mongoosePort);

const express = require('express');
const bodyParser = require('body-parser');

const auth = require('../middlewares/token_auth');

/**
 * rate Song requests.
 * @module rateSongsRoutes
*/
const rateSongsRoutes = (app, fs) => {

    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));

    /**
    * This function rates a song.
    * Then it updates the info of the rated Song.
    * @name put/rateSongs
    * @function
    * @memberof module:rateSongsRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the song's id generated by the mongoBD as requested from the postman.
    * @param {Number} rating it has the rating of the chosen song.
    * @param {Number} rateCount it has the number of how many times this song was rated.
    */

    app.put('/rateSongs', auth, (req, res) => {
        mongoose.connection.db.collection('songs', function(err, collection){
            collection.find({_id : new ObjectId (req.body.songId)})
            .toArray((err, docs) => {
                rateCount = docs[0].rateCount;
                if(rateCount == 0){
                    var avg = JSON.parse(req.body.rating);
                    collection.updateOne(
                        {_id: new ObjectId(req.body.songId)},
                        {$set:{rateCount : 1, rating : avg}},
                    );
                }else {
                    rating = docs[0].rating * rateCount;
                    rateCount++;
                    var newRating = JSON.parse(req.body.rating) + rating;
                    var avg = newRating/rateCount
                    collection.updateMany(
                        {_id: new ObjectId(req.body.songId)},
                        {$inc:{rateCount : 1}, $set:{rating : avg}},
      
                    );
                }
      
            });
        });
        res.end();
    });
};

module.exports = rateSongsRoutes;