const mongoose = require('mongoose');
var ObjectId = require('mongoose').Types.ObjectId;

const mongoosePort = require('../env_variables/env_vars.json').mongoosePort
mongoose.connect(mongoosePort);

const express = require('express');
const bodyParser = require('body-parser');

const auth = require('../middlewares/token_auth');
const artist_auth = require('../middlewares/artist_auth');

var Song = require('../Database Seeds/models/song');

/**
 * remix Song requests.
 * @module remixesRoutes
*/
const remixesRoutes = (app, fs) => {
    // showing song remix
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));

    /**
    * This function gets the remix of the song that the user requested for.
    * @name get/remixes/:remixId
    * @function
    * @memberof module:remixesRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the remix song's id generated by the mongoBD as requested from the postman.
    * @param {*} res it shows the available remixes of the song that the user requested.
    */

    app.get('/remixes/:remixId',(req, res) => {
        mongoose.connection.db.collection('songs',function(err, collection){
             collection.find({_id:new ObjectId(req.params.remixId)}).toArray(function(err,docs){
                    if (err) {
                        throw err;

                    }
                    res.send(docs[0]);
                });
        });
    });

    /**
    * This function creates a remix of the song that the user requested for. The user has to be an artist
    * it then updates the song info and the user info.
    * @name post/createRemix
    * @function
    * @memberof module:remixesRoutes
    * @inner
    * @param {*} req requesting the needed info from postman as the following:
    * @param {*} _id the user's id generated by the mongoBD as requested from the postman.
    * @param {*} res it shows the available remixes of the song that the user requested.
    * @param {Object} newRemix the new remix of the song
    * @param {string} name the name of the remix
    * @param {Number} year year of the remix release
    * @param {string} genre genre of the remix
    * @param {string} mood mood of the remix
    * @param {string} artist artist who made the remix
    * @param {Array} remixes the array of remixes name
    * @param {Array} uploadedSongs the array of the uploaded songs of the artist
    * @param {string} res sends a message to the user that either the artist created a remix successfully or not.
    */

    app.post('/createRemix', auth, artist_auth, (req, res) =>{
        mongoose.connection.db.collection('users', function(err, collection2){
            if (err){
                throw err;
            }
            collection2.find({type:"Artist"},{_id:new ObjectId(req.body.userId)}).toArray( function(err,docs) {
                if (err){
                    throw err
                }else{
                    mongoose.connection.db.collection('songs', function(err, collection){
                        if(err){
                            throw err;
                        }

                        var newRemix = new Song ({
                            name: req.body.remixName,
                            year: req.body.year,
                            genre: req.body.genre,
                            mood: req.body.mood,
                            artist: req.body.artist
                        });
      
                        newRemix.save(function(err, result) {
                          if (err) {
                            throw err;
                          }
                        });
                        collection.updateOne(
                            {_id: new ObjectId(req.body.songId)},
                            {$push:{ remixes :req.body.remixName}}
                        );
                    });
                  }
        });
      
        collection2.updateOne(
          {_id: new ObjectId(req.body.userId)},
          {$push:{ uploadedSongs :req.body.remixName}}
        );
      });
    res.send('new song created!')
  });
}

module.exports = remixesRoutes;